### ISSUE TITLE
unable to import v1.16.10

### ISSUE THREAD

**Issue by haoliangyu** [koopjs/winnow#128]
```
{ Error: Cannot find module 'winnow'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/linux/Documents/Repositories/output-ogcapi-features/src/route-handlers/get-collection-item.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }
```

v1.16.9 works fine.

**Comment by haoliangyu** [comment]
fixed with v1.16.11
