### ISSUE TITLE
can you provide browser distribution version?

### ISSUE THREAD

**Issue by hoogw** [koopjs/winnow#134]
I try to use browserify.js to generate the browser distribution version of it, so I can use script tag include it in browser use.

But, I get build error:  

can you try to build it see if you can success?

      `Last login: Mon Apr 27 16:28:49 on ttys003
       nicole@nicoles-iMac ~ % cd /Users/nicole/node/winnow 
       nicole@nicoles-iMac winnow % npm install
           npm WARN deprecated request@2.88.2: request has been deprecated, see       https://github.com/request/request/issues/3142

     > farmhash@3.0.0 install /Users/nicole/node/winnow/node_modules/farmhash
      > prebuild-install --runtime napi || prebuild-install || node-gyp rebuild

npm notice created a lockfile as package-lock.json. You should commit this file.
added 439 packages from 310 contributors and audited 1074 packages in 15.164s

33 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

nicole@nicoles-iMac winnow % browserify src/index.js --s winnow -o dist/winnow.js

/Users/nicole/node/winnow/node_modules/farmhash/build/Release/farmhash.node:1
����
   0���__TEXT�__text__TEXT�
                           �m�
                              �__stubs__TEXT�y ��__stub_helper__TEXT�z��z�__const__TEXT�|%�|__cstring__TEXT�}8�}__gcc_except_tab__TEXT��__unwind_info__TEXT�8�__eh_frame__TEXTX��
                 X��__DATA��__nl_symbol_ptr__DATA��0__got__DATA��2__la_symbol_ptr__DATA(��(�5__mod_init_func__DATA���	__data__DATA�����H__LINKEDIT�t�t"�0�  �Pp��`h�8�94�@
            P6��e�꤫�1=��X
                        ��$
^
ParseError: Unexpected character '�'`

**Comment by hoogw** [comment]
farmhash.js only works as native node fashion, only worked on sever, because of binding edge, it never worked on client browser.  

If winnow include farmhash, will brow out browserify.js, means failed.
You will never make a browser client version of winnow.js, unless, winnow exclude farmhash dependency.

webpack config node loader seems can load farmhash.node,  but, I doubt it will work, because 
farmhash never will work on browser. 

So if winnow accidently include farmhash, you could remove that dependency, so I can use browserify to build a browser distribution file.

**Comment by hoogw** [comment]
I comment out farmhash, in source code, remove all farmhash dependency.

Now I browserify it again, run into another error:  

                      ` browserify src/index.js --s winnow -o dist/winnow.js
                     Error: Cannot find module 'babelify' from '/Users/nicole/node/winnow/node_modules/wkt-parser'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:107:35
    at processDirs (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:260:39)
    at isdir (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:267:32)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:23:69
    at FSReqCallback.oncomplete (fs.js:166:21)`

**Comment by hoogw** [comment]
after install babelify, and babel, it works, but I run into another error:

                        `nicole@nicoles-iMac winnow % browserify src/index.js --s winnow -o dist/winnow.js
                          Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/nicole/node/winnow/node_modules/babel-preset-es2015/lib/index.js while parsing file: /Users/nicole/node/winnow/node_modules/wkt-parser/wkt.build.js
    at createDescriptor (/Users/nicole/node/winnow/node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
    at /Users/nicole/node/winnow/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (/Users/nicole/node/winnow/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/Users/nicole/node/winnow/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at /Users/nicole/node/winnow/node_modules/@babel/core/lib/config/config-descriptors.js:58:104
    at cachedFunction (/Users/nicole/node/winnow/node_modules/@babel/core/lib/config/caching.js:62:27)
    at cachedFunction.next (<anonymous>)
    at evaluateSync (/Users/nicole/node/winnow/node_modules/gensync/index.js:244:28)
    at sync (/Users/nicole/node/winnow/node_modules/gensync/index.js:84:14)
                        nicole@nicoles-iMac winnow % `

**Comment by hoogw** [comment]
here is call my script to run into error, 

4. is the last error, not sure how to solve, 1 to 3 error, I already fixed, by script below.

Please advise how to solve error #4?
                                 `

browserify src/index.js --s winnow -o dist/winnow.js 



        1) farmhash.node unexpected char error ,
                     remove all farmhash dependency from source code. 




        2) babelify not found
        
        
                     // global install not work, same error
                     nicole@nicoles-iMac ~ % sudo npm install -g babelify babel-plugin-transform-decorators-legacy babel-preset-es2015
                     
                     
                     
                     
                     //install local at winnow,
                     // package.json will be add those 3 dependency.
                     nicole@nicoles-iMac winnow % npm install babelify babel-preset-es2015
                     
                     
                     
                     
                     
         2.5) gyp: No Xcode or CLT version detected macOS Catalina 
         
                    https://medium.com/flawless-app-stories/gyp-no-xcode-or-clt-version-detected-macos-catalina-anansewaa-38b536389e8d            
                     
                     // check path use later
                     xcode-select --print-path
                     
                     // remove old one
                     sudo rm -r -f /Library/Developer/CommandLineTools
                     
                     
                     // install a new one
                     xcode-select --install
                     
                     
                     
                     
                     
                     
                     
         
         3) Error: Cannot find module '@babel/core'            
         
         // only use this one
         npm i @babel/plugin-proposal-class-properties @babel/preset-react @babel/preset-env @babel/core @babel/plugin-transform-runtime --save-dev
         
         
                     // babel 7
                     npm install --save-dev @babel/core @babel/preset-env
                     
                     
                     
                     // babel 6
                     npm install --save-dev babel-core babel-preset-env
                     
                     
                     
          4) error:
                       Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/nicole/node/winnow/node_modules/babel-preset-es2015/lib/index.js while parsing file: /Users/nicole/node/winnow/node_modules/wkt-parser/wkt.build.js           `
