### ISSUE TITLE
When returnGeometry is false and outSR is 102100 winnow throws an error

### ISSUE THREAD

**Issue by efbenson** [koopjs/winnow#94]
It seems contradictory to have them both sent, but AGOL does it when opening the grid of a layer in the map viewer and it throws a modal error.

![image](https://user-images.githubusercontent.com/976257/43161223-7ca280f0-8f55-11e8-9ecd-f52dbc80da24.png)

I console dir'ed the params for esrify and properties are null.

This is a regression at some point, it was working a before at 1.12.5
``` shell 

{ properties: undefined,
  geometry: undefined,
  dateFields: '',
  requiresObjectId: 'true',
  idField: 'OBJECTID' }
Trace: TypeError: Cannot read property 'OBJECTID' of undefined
    at Object.esriFy (F:\proj\htrack\src\mapping-api\node_modules\winnow\dist\sql.js:155:38)
    at alasql.Query.eval [as selectfn] (eval at yy.Select.compileSelect2 (F:\proj\htrack\src\mapping-api\node_modules\alasql\dist\alasql.fs.js:9734:9), <anonymous>:3:40)
    at doJoin (F:\proj\htrack\src\mapping-api\node_modules\alasql\dist\alasql.fs.js:7461:27)
    at doJoin (F:\proj\htrack\src\mapping-api\node_modules\alasql\dist\alasql.fs.js:7545:8)
    at queryfn3 (F:\proj\htrack\src\mapping-api\node_modules\alasql\dist\alasql.fs.js:6963:2)
    at queryfn2 (F:\proj\htrack\src\mapping-api\node_modules\alasql\dist\alasql.fs.js:6937:9)
    at Object.eval [as datafn] (eval at <anonymous> (F:\proj\htrack\src\mapping-api\node_modules\alasql\dist\alasql.fs.js:8415:20), <anonymous>:3:57)
    at F:\proj\htrack\src\mapping-api\node_modules\alasql\dist\alasql.fs.js:6885:19
    at Array.forEach (<anonymous>)
    at queryfn (F:\proj\htrack\src\mapping-api\node_modules\alasql\dist\alasql.fs.js:6881:16)
    at statement (F:\proj\htrack\src\mapping-api\node_modules\alasql\dist\alasql.fs.js:8026:14)
    at Function.alasql.dexec (F:\proj\htrack\src\mapping-api\node_modules\alasql\dist\alasql.fs.js:4619:11)
    at Function.alasql.exec (F:\proj\htrack\src\mapping-api\node_modules\alasql\dist\alasql.fs.js:4601:17)
    at alasql (F:\proj\htrack\src\mapping-api\node_modules\alasql\dist\alasql.fs.js:138:16)
    at standardQuery (F:\proj\htrack\src\mapping-api\node_modules\winnow\dist\executeQuery.js:34:18)
    at Object.Winnow.query (F:\proj\htrack\src\mapping-api\node_modules\winnow\dist\index.js:33:17)
    at query (F:\proj\htrack\src\mapping-api\node_modules\featureserver\dist\query.js:27:28)
    at execQuery (F:\proj\htrack\src\mapping-api\node_modules\featureserver\dist\route.js:36:16)
    at Object.route (F:\proj\htrack\src\mapping-api\node_modules\featureserver\dist\route.js:27:14)
    at F:\proj\htrack\src\mapping-api\node_modules\koop-output-geoservices\index.js:9:24
    at F:\proj\htrack\src\mapping-api\node_modules\koop\dist\models\index.js:15:9
    at route.then (F:\proj\htrack\src\mapping-api\lib\provider\model.js:40:13)
    at execQuery (F:\proj\htrack\src\mapping-api\node_modules\featureserver\dist\route.js:38:52)
    at Object.route (F:\proj\htrack\src\mapping-api\node_modules\featureserver\dist\route.js:27:14)
    at F:\proj\htrack\src\mapping-api\node_modules\koop-output-geoservices\index.js:9:24
    at F:\proj\htrack\src\mapping-api\node_modules\koop\dist\models\index.js:15:9
    at route.then (F:\proj\htrack\src\mapping-api\lib\provider\model.js:40:13)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by rgwozdz** [comment]
Can you provide the full request URL issued by AGOL that leads to this error?

**Comment by rgwozdz** [comment]
@efbenson - can you provide steps to reproduce? I have

1) Started koop server
2) Add a FeatureServer item to AGOL
3) Opened the new AGOL item in MapViewer
4) Opened the layer's attribute table

I get no modal error with the steps above.

**Comment by efbenson** [comment]
I played with postman and was enabling and disabling each param.  I found disabling returnGeometry being sent made it work, but returnGeometry by itself also worked.  A bunch of requests later it was narrowed to the 2.

```
.../koop/htrack-lastPositions/FeatureServer/0/query?f=json&where=1%3D1&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&orderByFields=dateTime%20ASC&outSR=102100&resultOffset=0&resultRecordCount=50
```

**Comment by rgwozdz** [comment]
It's just a warning, intended to let you know that you have set a metadata field named `receivedTime` that isn't showing up in the GeoJSON `properties` object (perhaps it's not being added in the translation function?).  If that warning is showing up for unrelated reasons, please let us know.  Thanks.
